name: GoneFishing
main: no.runsafe.gonefishing.GoneFishing
version: 1.0.@BUILD@
author: Kruithne
description: Fishing Tournament plug-in!
commands:
  gonefishing:
    description: Fishing Tournament commands.
    aliases: [gf]
